from callbacks import (
    data_loading,
    precompute,
    preview,
    profiling,
    target_iv,
    outlier,
    deep_dive,
    correlation,
    stat_tests,
    var_summary,
    playground,
    results,
    help_overlay,
    profile,
)
